// src/utils/exporters.js
// Client-side exports — no backend/deps. CSV opens in Excel; PDF via print.

const esc = (s) => String(s ?? '').replace(/[&<>"]/g, (c) => (
  { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]
))

// Download an Excel-friendly CSV. `rows` is an array of arrays.
export function downloadCsv(filename, headers, rows) {
  const cell = (v) => {
    const s = String(v ?? '')
    return /[",\n\r]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s
  }
  const lines = [headers.map(cell).join(',')]
  for (const r of rows) lines.push(r.map(cell).join(','))
  // BOM so Excel reads UTF-8 (₹, €, etc.) correctly.
  const blob = new Blob(['﻿' + lines.join('\r\n')], { type: 'text/csv;charset=utf-8;' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a); a.click(); a.remove()
  setTimeout(() => URL.revokeObjectURL(url), 1000)
}

// Open a printable report (a table) and trigger the print dialog → Save as PDF.
export function printTableReport({ title, subtitle = '', headers, rows, gymName = 'SynapX GymOS', logo = '' }) {
  const th  = headers.map(h => `<th>${esc(h)}</th>`).join('')
  const trs = rows.length
    ? rows.map(r => `<tr>${r.map(c => `<td>${esc(c)}</td>`).join('')}</tr>`).join('')
    : `<tr><td colspan="${headers.length}" style="text-align:center;color:#9CA3AF;padding:24px">No data</td></tr>`
  const when = new Date().toLocaleString('en-US', { dateStyle: 'medium', timeStyle: 'short' })

  const html = `<!doctype html><html><head><meta charset="utf-8"><title>${esc(title)}</title>
<style>
  * { box-sizing: border-box; }
  body { font-family: 'Inter', system-ui, Arial, sans-serif; color: #17181C; margin: 0; padding: 28px; }
  .top { display: flex; justify-content: space-between; align-items: flex-start; border-bottom: 2px solid #E11D2E; padding-bottom: 14px; margin-bottom: 18px; }
  .brand { display: flex; align-items: center; gap: 12px; }
  .brand img { width: 40px; height: 40px; border-radius: 9px; object-fit: cover; }
  .gym { font-size: 17px; font-weight: 800; }
  .muted { color: #6B7280; font-size: 12px; }
  h1 { font-size: 15px; margin: 0 0 2px; }
  table { width: 100%; border-collapse: collapse; font-size: 12px; }
  th { text-align: left; text-transform: uppercase; letter-spacing: 1px; font-size: 10px; color: #6B7280; border-bottom: 1px solid #E5E7EB; padding: 8px 10px; }
  td { padding: 8px 10px; border-bottom: 1px solid #F1F1F3; }
  tr:nth-child(even) td { background: #FAFAFB; }
  .foot { margin-top: 18px; color: #9CA3AF; font-size: 11px; text-align: center; }
  @media print { body { padding: 0; } }
</style></head>
<body>
  <div class="top">
    <div class="brand">
      ${logo ? `<img src="${logo}" alt="">` : ''}
      <div>
        <div class="gym">${esc(gymName)}</div>
        <div class="muted">${esc(subtitle)}</div>
      </div>
    </div>
    <div style="text-align:right">
      <h1>${esc(title)}</h1>
      <div class="muted">${esc(when)} · ${rows.length} rows</div>
    </div>
  </div>
  <table><thead><tr>${th}</tr></thead><tbody>${trs}</tbody></table>
  <div class="foot">Generated by ${esc(gymName)} · SynapX GymOS</div>
  <script>window.onload = function(){ window.print(); };</script>
</body></html>`

  const w = window.open('', '_blank', 'width=900,height=700')
  if (!w) return false
  w.document.open(); w.document.write(html); w.document.close()
  return true
}
